# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multikernel spawn support
#

obj-y += spawn.o dtb.o dtb_of.o dtb_devices.o dtb_pci.o
obj-$(CONFIG_ACPI) += dtb_acpi.o
obj-$(CONFIG_MULTIKERNEL_ITS_PROXY) += its_proxy.o
